# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login_main(object):
    def setupUi(self, Login_main):
        Login_main.setObjectName("Login_main")
        Login_main.setWindowModality(QtCore.Qt.NonModal)
        Login_main.resize(791, 614)
        Login_main.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        Login_main.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        Login_main.setFont(font)
        Login_main.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        Login_main.setToolTipDuration(-1)
        Login_main.setLayoutDirection(QtCore.Qt.LeftToRight)
        Login_main.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(Login_main)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(30, 0, 741, 621))
        self.widget.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.widget.setAutoFillBackground(False)
        self.widget.setStyleSheet("QPushButton#btn_ok{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(85, 98, 112, 226), stop:1 rgba(11, 131, 120, 219));\n"
"    color: rgba(255,255,255,210);\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton#btn_ok:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(85, 81, 84, 226), stop:1 rgba(150, 123, 111, 219));\n"
"}\n"
"QPushButton#btn_ok:pressed{\n"
"    padding-left: 5px;\n"
"    padding-top: 5px;\n"
"    background-color: rgba(68, 46, 35 ,255);\n"
"}\n"
"\n"
"QPushButton#btn_cc{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(11, 131, 120, 219), stop:1 rgba(85, 98, 112, 226));\n"
"    color: rgba(255,255,255,210);\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton#btn_cc:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(150, 123, 111, 219), stop:1 rgba(85, 81, 84, 226));\n"
"}\n"
"QPushButton#btn_cc:pressed{\n"
"    padding-left: 5px;\n"
"    padding-top: 5px;\n"
"    background-color: rgba(68, 46, 35 ,255);\n"
"}\n"
"color: rgb(68, 46, 35);")
        self.widget.setObjectName("widget")
        self.btn_ok = QtWidgets.QPushButton(self.widget)
        self.btn_ok.setGeometry(QtCore.QRect(590, 360, 75, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_ok.setFont(font)
        self.btn_ok.setStyleSheet("")
        self.btn_ok.setObjectName("btn_ok")
        self.btn_cc = QtWidgets.QPushButton(self.widget)
        self.btn_cc.setGeometry(QtCore.QRect(500, 360, 75, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_cc.setFont(font)
        self.btn_cc.setStyleSheet("")
        self.btn_cc.setObjectName("btn_cc")
        self.txt_lbl = QtWidgets.QLabel(self.widget)
        self.txt_lbl.setGeometry(QtCore.QRect(510, 410, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txt_lbl.setFont(font)
        self.txt_lbl.setStyleSheet("color: rgb(255, 0, 0);")
        self.txt_lbl.setText("")
        self.txt_lbl.setObjectName("txt_lbl")
        self.txt_pw = QtWidgets.QLineEdit(self.widget)
        self.txt_pw.setGeometry(QtCore.QRect(490, 310, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txt_pw.setFont(font)
        self.txt_pw.setStyleSheet("background-color: rgb(0, 0, 0,0);\n"
"border: none;\n"
"border-bottom:2px solid rgb(46,82,101,200);\n"
"color:rgb(0,0,0,240);\n"
"padding-bottom: 7px;")
        self.txt_pw.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txt_pw.setObjectName("txt_pw")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(410, 260, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(520, 190, 141, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:rgba(0,0,0,200);")
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(380, 320, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.txt_user = QtWidgets.QLineEdit(self.widget)
        self.txt_user.setGeometry(QtCore.QRect(490, 250, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txt_user.setFont(font)
        self.txt_user.setStyleSheet("background-color: rgb(0, 0, 0,0);\n"
"border: none;\n"
"border-bottom:2px solid rgb(46,82,101,200);\n"
"color:rgb(0,0,0,240);\n"
"padding-bottom: 7px;")
        self.txt_user.setObjectName("txt_user")
        self.image_cafe = QtWidgets.QLabel(self.widget)
        self.image_cafe.setEnabled(True)
        self.image_cafe.setGeometry(QtCore.QRect(40, 10, 381, 591))
        self.image_cafe.setStyleSheet("border-image: url(:/image/dienthoai-11-675x1200-24.jpg);\n"
"border-top-left-radius: 50px;")
        self.image_cafe.setText("")
        self.image_cafe.setObjectName("image_cafe")
        self.image_login = QtWidgets.QLabel(self.widget)
        self.image_login.setGeometry(QtCore.QRect(370, 10, 351, 591))
        self.image_login.setStyleSheet("\n"
"border-bottom-right-radius: 50px;\n"
"background-color: rgb(255, 255, 255);")
        self.image_login.setText("")
        self.image_login.setObjectName("image_login")
        self.btn_x = QtWidgets.QPushButton(self.widget)
        self.btn_x.setGeometry(QtCore.QRect(680, 10, 41, 28))
        self.btn_x.setStyleSheet("QPushButton#btn_x{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(11, 131, 120, 219), stop:1 rgba(85, 98, 112, 226));\n"
"    color: rgba(255,255,255,210);\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton#btn_x:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(150, 123, 111, 219), stop:1 rgba(85, 81, 84, 226));\n"
"}\n"
"QPushButton#btn_x:pressed{\n"
"    padding-left: 5px;\n"
"    padding-top: 5px;\n"
"    background-color: rgba(150, 123, 111,255);\n"
"}")
        self.btn_x.setObjectName("btn_x")
        self.image_cafe.raise_()
        self.image_login.raise_()
        self.txt_lbl.raise_()
        self.txt_pw.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.txt_user.raise_()
        self.btn_cc.raise_()
        self.btn_ok.raise_()
        self.btn_x.raise_()
        Login_main.setCentralWidget(self.centralwidget)

        self.retranslateUi(Login_main)
        QtCore.QMetaObject.connectSlotsByName(Login_main)

    def retranslateUi(self, Login_main):
        _translate = QtCore.QCoreApplication.translate
        Login_main.setWindowTitle(_translate("Login_main", "Login"))
        self.btn_ok.setText(_translate("Login_main", "OK"))
        self.btn_cc.setText(_translate("Login_main", "Cancel"))
        self.label.setText(_translate("Login_main", "User"))
        self.label_3.setText(_translate("Login_main", "LOG IN"))
        self.label_2.setText(_translate("Login_main", "Password"))
        self.btn_x.setText(_translate("Login_main", "X"))
# import pic_login_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Login_main = QtWidgets.QMainWindow()
    ui = Ui_Login_main()
    ui.setupUi(Login_main)
    Login_main.show()
    sys.exit(app.exec_())
