# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'manager.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_manager(object):
    def setupUi(self, manager):
        manager.setObjectName("manager")
        manager.resize(700, 422)
        manager.setStyleSheet("QPushButton#btn_b1{\n"
"background-color: rgba(16, 30, 41, 240);\n"
"color: rgba(255,255,255,200);\n"
"border-radius: 5px;\n"
"}\n"
"QPushButton#btn_b1:pressed{\n"
"padding-left: 5px;\n"
"padding-top: 5px;\n"
"background-color: rgba(16, 30, 41,100);\n"
"backgound-posotion:calc(100%-10px)center;\n"
"}\n"
"QPushButton#btn_b1:hover{\n"
"backgound-color: rgba(16, 30, 41,200);\n"
"}\n"
"\n"
"\n"
"QPushButton#btn_b2{\n"
"background-color: rgba(16, 30, 41, 240);\n"
"color: rgba(255,255,255,200);\n"
"border-radius: 5px;\n"
"}\n"
"QPushButton#btn_b2:pressed{\n"
"padding-left: 5px;\n"
"padding-top: 5px;\n"
"background-color: rgba(16, 30, 41,100);\n"
"backgound-posotion:calc(100%-10px)center;\n"
"}\n"
"QPushButton#btn_b2:hover{\n"
"backgound-color: rgba(16, 30, 41,200);\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"QPushButton#btn_b3{\n"
"background-color: rgba(16, 30, 41, 240);\n"
"color: rgba(255,255,255,200);\n"
"border-radius: 5px;\n"
"}\n"
"QPushButton#btn_b3:pressed{\n"
"padding-left: 5px;\n"
"padding-top: 5px;\n"
"background-color: rgba(16, 30, 41,100);\n"
"backgound-posotion:calc(100%-10px)center;\n"
"}\n"
"QPushButton#btn_b3:hover{\n"
"backgound-color: rgba(16, 30, 41,200);\n"
"}\n"
"\n"
"QPushButton#btn_b4{\n"
"background-color: rgba(16, 30, 41, 240);\n"
"color: rgba(255,255,255,200);\n"
"border-radius: 5px;\n"
"}\n"
"QPushButton#btn_b4:pressed{\n"
"padding-left: 5px;\n"
"padding-top: 5px;\n"
"background-color: rgba(16, 30, 41,100);\n"
"backgound-posotion:calc(100%-10px)center;\n"
"}\n"
"QPushButton#btn_b4:hover{\n"
"backgound-color: rgba(16, 30, 41,200);\n"
"}\n"
"\n"
"\n"
"QPushButton#btn_b5{\n"
"background-color: rgba(16, 30, 41, 240);\n"
"color: rgba(255,255,255,200);\n"
"border-radius: 5px;\n"
"}\n"
"QPushButton#btn_b5:pressed{\n"
"padding-left: 5px;\n"
"padding-top: 5px;\n"
"background-color: rgba(16, 30, 41,100);\n"
"backgound-posotion:calc(100%-10px)center;\n"
"}\n"
"QPushButton#btn_b5:hover{\n"
"backgound-color: rgba(16, 30, 41,200);\n"
"}\n"
"\n"
"\n"
"QPushButton#btn_b6{\n"
"background-color: rgba(16, 30, 41, 240);\n"
"color: rgba(255,255,255,200);\n"
"border-radius: 5px;\n"
"}\n"
"QPushButton#btn_b6:pressed{\n"
"padding-left: 5px;\n"
"padding-top: 5px;\n"
"background-color: rgba(16, 30, 41,100);\n"
"backgound-posotion:calc(100%-10px)center;\n"
"}\n"
"QPushButton#btn_b6:hover{\n"
"backgound-color: rgba(16, 30, 41,200);\n"
"}\n"
"\n"
"\n"
"QPushButton#btn_b7{\n"
"background-color: rgba(16, 30, 41, 240);\n"
"color: rgba(255,255,255,200);\n"
"border-radius: 5px;\n"
"}\n"
"QPushButton#btn_b7:pressed{\n"
"padding-left: 5px;\n"
"padding-top: 5px;\n"
"background-color: rgba(16, 30, 41,100);\n"
"backgound-posotion:calc(100%-10px)center;\n"
"}\n"
"QPushButton#btn_b7:hover{\n"
"backgound-color: rgba(16, 30, 41,200);\n"
"}\n"
"\n"
"QPushButton#btn_b8{\n"
"background-color: rgba(16, 30, 41, 240);\n"
"color: rgba(255,255,255,200);\n"
"border-radius: 5px;\n"
"}\n"
"QPushButton#btn_b8:pressed{\n"
"padding-left: 5px;\n"
"padding-top: 5px;\n"
"background-color: rgba(16, 30, 41,100);\n"
"backgound-posotion:calc(100%-10px)center;\n"
"}\n"
"QPushButton#btn_b8:hover{\n"
"backgound-color: rgba(16, 30, 41,200);\n"
"}\n"
"\n"
"QPushButton#btn_b9{\n"
"background-color: rgba(16, 30, 41, 240);\n"
"color: rgba(255,255,255,200);\n"
"border-radius: 5px;\n"
"}\n"
"QPushButton#btn_b9:pressed{\n"
"padding-left: 5px;\n"
"padding-top: 5px;\n"
"background-color: rgba(16, 30, 41,100);\n"
"backgound-posotion:calc(100%-10px)center;\n"
"}\n"
"QPushButton#btn_b9:hover{\n"
"backgound-color: rgba(16, 30, 41,200);\n"
"}\n"
"\n"
"\n"
"QPushButton#btn_b10{\n"
"background-color: rgba(16, 30, 41, 240);\n"
"color: rgba(255,255,255,200);\n"
"border-radius: 5px;\n"
"}\n"
"QPushButton#btn_b10:pressed{\n"
"padding-left: 5px;\n"
"padding-top: 5px;\n"
"background-color: rgba(16, 30, 41,100);\n"
"backgound-posotion:calc(100%-10px)center;\n"
"}\n"
"QPushButton#btn_b10:hover{\n"
"backgound-color: rgba(16, 30, 41,200);\n"
"}\n"
"\n"
"QPushButton#btn_b11{\n"
"background-color: rgba(16, 30, 41, 240);\n"
"color: rgba(255,255,255,200);\n"
"border-radius: 5px;\n"
"}\n"
"QPushButton#btn_b11:pressed{\n"
"padding-left: 5px;\n"
"padding-top: 5px;\n"
"background-color: rgba(16, 30, 41,100);\n"
"backgound-posotion:calc(100%-10px)center;\n"
"}\n"
"QPushButton#btn_b11:hover{\n"
"backgound-color: rgba(16, 30, 41,200);\n"
"}\n"
"\n"
"QPushButton#btn_b12{\n"
"background-color: rgba(16, 30, 41, 240);\n"
"color: rgba(255,255,255,200);\n"
"border-radius: 5px;\n"
"}\n"
"QPushButton#btn_b12:pressed{\n"
"padding-left: 5px;\n"
"padding-top: 5px;\n"
"background-color: rgba(16, 30, 41,100);\n"
"backgound-posotion:calc(100%-10px)center;\n"
"}\n"
"QPushButton#btn_b12:hover{\n"
"backgound-color: rgba(16, 30, 41,200);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(manager)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 10, 711, 431))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("\n"
"border-radius: 5px;\n"
"")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.btn_b1 = QtWidgets.QPushButton(self.tab)
        self.btn_b1.setGeometry(QtCore.QRect(10, 10, 75, 70))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_b1.setFont(font)
        self.btn_b1.setStyleSheet("")
        self.btn_b1.setObjectName("btn_b1")
        self.btn_b2 = QtWidgets.QPushButton(self.tab)
        self.btn_b2.setGeometry(QtCore.QRect(100, 10, 75, 70))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_b2.setFont(font)
        self.btn_b2.setStyleSheet("")
        self.btn_b2.setObjectName("btn_b2")
        self.btn_b4 = QtWidgets.QPushButton(self.tab)
        self.btn_b4.setGeometry(QtCore.QRect(10, 90, 75, 70))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_b4.setFont(font)
        self.btn_b4.setStyleSheet("")
        self.btn_b4.setObjectName("btn_b4")
        self.btn_b7 = QtWidgets.QPushButton(self.tab)
        self.btn_b7.setGeometry(QtCore.QRect(10, 170, 75, 70))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_b7.setFont(font)
        self.btn_b7.setStyleSheet("")
        self.btn_b7.setObjectName("btn_b7")
        self.btn_b10 = QtWidgets.QPushButton(self.tab)
        self.btn_b10.setGeometry(QtCore.QRect(10, 250, 75, 70))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_b10.setFont(font)
        self.btn_b10.setStyleSheet("")
        self.btn_b10.setObjectName("btn_b10")
        self.btn_b5 = QtWidgets.QPushButton(self.tab)
        self.btn_b5.setGeometry(QtCore.QRect(100, 90, 75, 70))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_b5.setFont(font)
        self.btn_b5.setStyleSheet("")
        self.btn_b5.setObjectName("btn_b5")
        self.btn_b8 = QtWidgets.QPushButton(self.tab)
        self.btn_b8.setGeometry(QtCore.QRect(100, 170, 75, 70))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_b8.setFont(font)
        self.btn_b8.setStyleSheet("")
        self.btn_b8.setObjectName("btn_b8")
        self.btn_b11 = QtWidgets.QPushButton(self.tab)
        self.btn_b11.setGeometry(QtCore.QRect(100, 250, 75, 70))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_b11.setFont(font)
        self.btn_b11.setStyleSheet("")
        self.btn_b11.setObjectName("btn_b11")
        self.btn_b6 = QtWidgets.QPushButton(self.tab)
        self.btn_b6.setGeometry(QtCore.QRect(190, 90, 75, 70))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_b6.setFont(font)
        self.btn_b6.setStyleSheet("")
        self.btn_b6.setObjectName("btn_b6")
        self.btn_b9 = QtWidgets.QPushButton(self.tab)
        self.btn_b9.setGeometry(QtCore.QRect(190, 170, 75, 70))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_b9.setFont(font)
        self.btn_b9.setStyleSheet("")
        self.btn_b9.setObjectName("btn_b9")
        self.btn_b12 = QtWidgets.QPushButton(self.tab)
        self.btn_b12.setGeometry(QtCore.QRect(190, 250, 75, 70))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_b12.setFont(font)
        self.btn_b12.setStyleSheet("")
        self.btn_b12.setObjectName("btn_b12")
        self.btn_b3 = QtWidgets.QPushButton(self.tab)
        self.btn_b3.setGeometry(QtCore.QRect(190, 10, 75, 70))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_b3.setFont(font)
        self.btn_b3.setStyleSheet("")
        self.btn_b3.setObjectName("btn_b3")
        self.btn_tt = QtWidgets.QPushButton(self.tab)
        self.btn_tt.setGeometry(QtCore.QRect(560, 330, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_tt.setFont(font)
        self.btn_tt.setStyleSheet("QPushButton#btn_tt{\n"
"background-color: rgba(2, 65, 118, 255);\n"
"color: rgba(255,255,255,200);\n"
"border-radius: 5px;\n"
"}\n"
"QPushButton#btn_tt:pressed{\n"
"padding-left: 5px;\n"
"padding-top: 5px;\n"
"background-color: rgba(2, 65, 118,100);\n"
"backgound-posotion:calc(100%-10px)center;\n"
"}\n"
"QPushButton#btn_tt:hover{\n"
"backgound-color: rgba(2, 65, 118,200);\n"
"}")
        self.btn_tt.setObjectName("btn_tt")
        self.comboBox = QtWidgets.QComboBox(self.tab)
        self.comboBox.setGeometry(QtCore.QRect(280, 11, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("background-color: rgba(16, 30, 41, 240)  ;\n"
"color: rgba(255,255,255,200);")
        self.comboBox.setObjectName("comboBox")
        self.btn_add = QtWidgets.QPushButton(self.tab)
        self.btn_add.setGeometry(QtCore.QRect(620, 10, 75, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_add.setFont(font)
        self.btn_add.setStyleSheet("QPushButton#btn_add{\n"
"background-color: rgba(2, 65, 118, 255);\n"
"color: rgba(255,255,255,200);\n"
"border-radius: 5px;\n"
"}\n"
"QPushButton#btn_add:pressed{\n"
"padding-left: 5px;\n"
"padding-top: 5px;\n"
"background-color: rgba(2, 65, 118,100);\n"
"backgound-posotion:calc(100%-10px)center;\n"
"}\n"
"QPushButton#btn_add:hover{\n"
"backgound-color: rgba(2, 65, 118,200);\n"
"}")
        self.btn_add.setObjectName("btn_add")
        self.spinBox = QtWidgets.QSpinBox(self.tab)
        self.spinBox.setGeometry(QtCore.QRect(550, 10, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.spinBox.setFont(font)
        self.spinBox.setStyleSheet("background-color: rgba(16, 30, 41, 240)  ;\n"
"color: rgba(255,255,255,200);")
        self.spinBox.setObjectName("spinBox")
        self.txt_b = QtWidgets.QLineEdit(self.tab)
        self.txt_b.setGeometry(QtCore.QRect(330, 50, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.txt_b.setFont(font)
        self.txt_b.setStyleSheet("background-color: rgba(16, 30, 41, 240)  ;\n"
"color: rgba(255,255,255,200);")
        self.txt_b.setObjectName("txt_b")
        self.btn_upd = QtWidgets.QPushButton(self.tab)
        self.btn_upd.setGeometry(QtCore.QRect(420, 330, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_upd.setFont(font)
        self.btn_upd.setStyleSheet("QPushButton#btn_upd{\n"
"background-color: rgba(2, 65, 118, 255);\n"
"color: rgba(255,255,255,200);\n"
"border-radius: 5px;\n"
"}\n"
"QPushButton#btn_upd:pressed{\n"
"padding-left: 5px;\n"
"padding-top: 5px;\n"
"background-color: rgba(2, 65, 118,100);\n"
"backgound-posotion:calc(100%-10px)center;\n"
"}\n"
"QPushButton#btn_upd:hover{\n"
"backgound-color: rgba(2, 65, 118,200);\n"
"}")
        self.btn_upd.setObjectName("btn_upd")
        self.btn_xoa = QtWidgets.QPushButton(self.tab)
        self.btn_xoa.setGeometry(QtCore.QRect(280, 330, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_xoa.setFont(font)
        self.btn_xoa.setStyleSheet("QPushButton#btn_xoa{\n"
"background-color: rgba(2, 65, 118, 255);\n"
"color: rgba(255,255,255,200);\n"
"border-radius: 5px;\n"
"}\n"
"QPushButton#btn_xoa:pressed{\n"
"padding-left: 5px;\n"
"padding-top: 5px;\n"
"background-color: rgba(2, 65, 118,100);\n"
"backgound-posotion:calc(100%-10px)center;\n"
"}\n"
"QPushButton#btn_xoa:hover{\n"
"backgound-color: rgba(2, 65, 118,200);\n"
"}")
        self.btn_xoa.setObjectName("btn_xoa")
        self.txt_money = QtWidgets.QLineEdit(self.tab)
        self.txt_money.setGeometry(QtCore.QRect(580, 50, 113, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.txt_money.setFont(font)
        self.txt_money.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.txt_money.setStyleSheet("background-color: rgba(16, 30, 41, 240)  ;\n"
"color: rgba(255,255,255,200);")
        self.txt_money.setObjectName("txt_money")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(290, 50, 47, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(490, 50, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.btn_b0 = QtWidgets.QPushButton(self.tab)
        self.btn_b0.setGeometry(QtCore.QRect(10, 330, 255, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_b0.setFont(font)
        self.btn_b0.setStyleSheet("QPushButton#btn_b0{\n"
"background-color: rgba(2, 65, 118, 255);\n"
"color: rgba(255,255,255,200);\n"
"border-radius: 5px;\n"
"}\n"
"QPushButton#btn_b0:pressed{\n"
"padding-left: 5px;\n"
"padding-top: 5px;\n"
"background-color: rgba(2, 65, 118,100);\n"
"backgound-posotion:calc(100%-10px)center;\n"
"}\n"
"QPushButton#btn_b0:hover{\n"
"backgound-color: rgba(2, 65, 118,200);\n"
"}")
        self.btn_b0.setObjectName("btn_b0")
        self.table_bill = QtWidgets.QTableWidget(self.tab)
        self.table_bill.setGeometry(QtCore.QRect(280, 90, 411, 231))
        self.table_bill.setStyleSheet("QTableWidget{\n"
"background-color: rgba(16, 30, 41, 240) ;\n"
"color: rgba(255,255,255,200);\n"
"padding: 2px\n"
"}\n"
"")
        self.table_bill.setObjectName("table_bill")
        self.table_bill.setColumnCount(4)
        self.table_bill.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.table_bill.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.table_bill.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.table_bill.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.table_bill.setHorizontalHeaderItem(3, item)
        self.btn_b2.raise_()
        self.btn_b4.raise_()
        self.btn_b7.raise_()
        self.btn_b10.raise_()
        self.btn_b5.raise_()
        self.btn_b8.raise_()
        self.btn_b11.raise_()
        self.btn_b6.raise_()
        self.btn_b9.raise_()
        self.btn_b12.raise_()
        self.btn_b3.raise_()
        self.btn_tt.raise_()
        self.comboBox.raise_()
        self.btn_add.raise_()
        self.spinBox.raise_()
        self.txt_b.raise_()
        self.btn_upd.raise_()
        self.btn_xoa.raise_()
        self.txt_money.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.btn_b0.raise_()
        self.btn_b1.raise_()
        self.table_bill.raise_()
        self.tabWidget.addTab(self.tab, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.table_bill_ngay = QtWidgets.QTableWidget(self.tab_4)
        self.table_bill_ngay.setGeometry(QtCore.QRect(20, 10, 311, 351))
        self.table_bill_ngay.setMinimumSize(QtCore.QSize(0, 0))
        self.table_bill_ngay.setMaximumSize(QtCore.QSize(16777215, 381))
        self.table_bill_ngay.setStyleSheet("QTableWidget{\n"
"background-color: rgba(16, 30, 41, 240) ;\n"
"color: rgba(255,255,255,200);\n"
"padding: 2px\n"
"}\n"
"")
        self.table_bill_ngay.setObjectName("table_bill_ngay")
        self.table_bill_ngay.setColumnCount(3)
        self.table_bill_ngay.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.table_bill_ngay.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.table_bill_ngay.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.table_bill_ngay.setHorizontalHeaderItem(2, item)
        self.table_bill_thang = QtWidgets.QTableWidget(self.tab_4)
        self.table_bill_thang.setGeometry(QtCore.QRect(480, 10, 201, 351))
        self.table_bill_thang.setStyleSheet("QTableWidget{\n"
"background-color: rgba(16, 30, 41, 240) ;\n"
"color: rgba(255,255,255,200);\n"
"padding: 2px\n"
"}\n"
"")
        self.table_bill_thang.setObjectName("table_bill_thang")
        self.table_bill_thang.setColumnCount(2)
        self.table_bill_thang.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.table_bill_thang.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.table_bill_thang.setHorizontalHeaderItem(1, item)
        self.btn_add_2 = QtWidgets.QPushButton(self.tab_4)
        self.btn_add_2.setGeometry(QtCore.QRect(360, 170, 93, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_add_2.setFont(font)
        self.btn_add_2.setStyleSheet("QPushButton#btn_add_2{\n"
"background-color: rgba(2, 65, 118, 255);\n"
"color: rgba(255,255,255,200);\n"
"border-radius: 5px;\n"
"}\n"
"QPushButton#btn_add_2:pressed{\n"
"padding-left: 5px;\n"
"padding-top: 5px;\n"
"background-color: rgba(2, 65, 118,100);\n"
"backgound-posotion:calc(100%-10px)center;\n"
"}\n"
"QPushButton#btn_add_2:hover{\n"
"backgound-color: rgba(2, 65, 118,200);\n"
"}")
        self.btn_add_2.setObjectName("btn_add_2")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.table_menu = QtWidgets.QTableWidget(self.tab_3)
        self.table_menu.setGeometry(QtCore.QRect(400, 10, 221, 351))
        self.table_menu.setStyleSheet("QTableWidget{\n"
"background-color: rgba(16, 30, 41, 240) ;\n"
"color: rgba(255,255,255,200);\n"
"padding: 2px\n"
"}\n"
"")
        self.table_menu.setObjectName("table_menu")
        self.table_menu.setColumnCount(2)
        self.table_menu.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.table_menu.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.table_menu.setHorizontalHeaderItem(1, item)
        self.label_8 = QtWidgets.QLabel(self.tab_3)
        self.label_8.setGeometry(QtCore.QRect(40, 130, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.tab_3)
        self.label_9.setGeometry(QtCore.QRect(80, 180, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.btn_upd_menu = QtWidgets.QPushButton(self.tab_3)
        self.btn_upd_menu.setGeometry(QtCore.QRect(140, 240, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_upd_menu.setFont(font)
        self.btn_upd_menu.setStyleSheet("QPushButton#btn_upd_menu{\n"
"background-color: rgba(2, 65, 118, 255);\n"
"color: rgba(255,255,255,200);\n"
"border-radius: 5px;\n"
"}\n"
"QPushButton#btn_upd_menu:pressed{\n"
"padding-left: 5px;\n"
"padding-top: 5px;\n"
"background-color: rgba(2, 65, 118,100);\n"
"backgound-posotion:calc(100%-10px)center;\n"
"}\n"
"QPushButton#btn_upd_menu:hover{\n"
"backgound-color: rgba(2, 65, 118,200);\n"
"}")
        self.btn_upd_menu.setObjectName("btn_upd_menu")
        self.label_10 = QtWidgets.QLabel(self.tab_3)
        self.label_10.setGeometry(QtCore.QRect(140, 60, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.lbl_menu = QtWidgets.QLabel(self.tab_3)
        self.lbl_menu.setGeometry(QtCore.QRect(80, 290, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_menu.setFont(font)
        self.lbl_menu.setStyleSheet("color: rgb(255, 0, 0);")
        self.lbl_menu.setObjectName("lbl_menu")
        self.txt_drink = QtWidgets.QLineEdit(self.tab_3)
        self.txt_drink.setGeometry(QtCore.QRect(120, 130, 171, 31))
        self.txt_drink.setStyleSheet("background-color: rgba(16, 30, 41, 240)  ;\n"
"color: rgba(255,255,255,200);")
        self.txt_drink.setObjectName("txt_drink")
        self.txt_unit = QtWidgets.QLineEdit(self.tab_3)
        self.txt_unit.setGeometry(QtCore.QRect(120, 180, 171, 31))
        self.txt_unit.setStyleSheet("background-color: rgba(16, 30, 41, 240)  ;\n"
"color: rgba(255,255,255,200);")
        self.txt_unit.setObjectName("txt_unit")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.btn_logout = QtWidgets.QPushButton(self.tab_2)
        self.btn_logout.setGeometry(QtCore.QRect(140, 270, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_logout.setFont(font)
        self.btn_logout.setStyleSheet("QPushButton#btn_logout{\n"
"background-color: rgba(2, 65, 118, 255);\n"
"color: rgba(255,255,255,200);\n"
"border-radius: 5px;\n"
"}\n"
"QPushButton#btn_logout:pressed{\n"
"padding-left: 5px;\n"
"padding-top: 5px;\n"
"background-color: rgba(2, 65, 118,100);\n"
"backgound-posotion:calc(100%-10px)center;\n"
"}\n"
"QPushButton#btn_logout:hover{\n"
"backgound-color: rgba(2, 65, 118,200);\n"
"}")
        self.btn_logout.setObjectName("btn_logout")
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setGeometry(QtCore.QRect(10, 80, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(10, 130, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setGeometry(QtCore.QRect(10, 180, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setGeometry(QtCore.QRect(10, 230, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.txt_name = QtWidgets.QLineEdit(self.tab_2)
        self.txt_name.setGeometry(QtCore.QRect(90, 80, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txt_name.setFont(font)
        self.txt_name.setStyleSheet("background-color: rgba(16, 30, 41, 240)  ;\n"
"color: rgba(255,255,255,200);")
        self.txt_name.setObjectName("txt_name")
        self.txt_phone = QtWidgets.QLineEdit(self.tab_2)
        self.txt_phone.setGeometry(QtCore.QRect(90, 130, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txt_phone.setFont(font)
        self.txt_phone.setStyleSheet("background-color: rgba(16, 30, 41, 240)  ;\n"
"color: rgba(255,255,255,200);")
        self.txt_phone.setObjectName("txt_phone")
        self.txt_id = QtWidgets.QLineEdit(self.tab_2)
        self.txt_id.setGeometry(QtCore.QRect(90, 180, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txt_id.setFont(font)
        self.txt_id.setStyleSheet("background-color: rgba(16, 30, 41, 240)  ;\n"
"color: rgba(255,255,255,200);")
        self.txt_id.setObjectName("txt_id")
        self.txt_pass = QtWidgets.QLineEdit(self.tab_2)
        self.txt_pass.setGeometry(QtCore.QRect(90, 230, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txt_pass.setFont(font)
        self.txt_pass.setStyleSheet("background-color: rgba(16, 30, 41, 240)  ;\n"
"color: rgba(255,255,255,200);")
        self.txt_pass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txt_pass.setObjectName("txt_pass")
        self.btn_add_acc = QtWidgets.QPushButton(self.tab_2)
        self.btn_add_acc.setGeometry(QtCore.QRect(40, 270, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_add_acc.setFont(font)
        self.btn_add_acc.setStyleSheet("QPushButton#btn_add_acc{\n"
"background-color: rgba(2, 65, 118, 255);\n"
"color: rgba(255,255,255,200);\n"
"border-radius: 5px;\n"
"}\n"
"QPushButton#btn_add_acc:pressed{\n"
"padding-left: 5px;\n"
"padding-top: 5px;\n"
"background-color: rgba(2, 65, 118,100);\n"
"backgound-posotion:calc(100%-10px)center;\n"
"}\n"
"QPushButton#btn_add_acc:hover{\n"
"backgound-color: rgba(2, 65, 118,200);\n"
"}")
        self.btn_add_acc.setObjectName("btn_add_acc")
        self.table_acc = QtWidgets.QTableWidget(self.tab_2)
        self.table_acc.setGeometry(QtCore.QRect(270, 10, 421, 341))
        self.table_acc.setStyleSheet("QTableWidget{\n"
"background-color: rgba(16, 30, 41, 240) ;\n"
"color: rgba(255,255,255,200);\n"
"padding: 2px\n"
"}\n"
"")
        self.table_acc.setObjectName("table_acc")
        self.table_acc.setColumnCount(4)
        self.table_acc.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.table_acc.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.table_acc.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.table_acc.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.table_acc.setHorizontalHeaderItem(3, item)
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setGeometry(QtCore.QRect(70, 20, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lbl_acc = QtWidgets.QLabel(self.tab_2)
        self.lbl_acc.setGeometry(QtCore.QRect(20, 310, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_acc.setFont(font)
        self.lbl_acc.setStyleSheet("color: rgb(255, 0, 0);")
        self.lbl_acc.setObjectName("lbl_acc")
        self.tabWidget.addTab(self.tab_2, "")
        manager.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(manager)
        self.statusbar.setObjectName("statusbar")
        manager.setStatusBar(self.statusbar)

        self.retranslateUi(manager)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(manager)

    def retranslateUi(self, manager):
        _translate = QtCore.QCoreApplication.translate
        manager.setWindowTitle(_translate("manager", "Quản lý"))
        self.btn_b1.setText(_translate("manager", "BÀN 1"))
        self.btn_b2.setText(_translate("manager", "BÀN 2"))
        self.btn_b4.setText(_translate("manager", "BÀN 4"))
        self.btn_b7.setText(_translate("manager", "BÀN 7"))
        self.btn_b10.setText(_translate("manager", "BÀN 10"))
        self.btn_b5.setText(_translate("manager", "BÀN 5"))
        self.btn_b8.setText(_translate("manager", "BÀN 8"))
        self.btn_b11.setText(_translate("manager", "BÀN 11"))
        self.btn_b6.setText(_translate("manager", "BÀN 6"))
        self.btn_b9.setText(_translate("manager", "BÀN 9"))
        self.btn_b12.setText(_translate("manager", "BÀN 12"))
        self.btn_b3.setText(_translate("manager", "BÀN 3"))
        self.btn_tt.setText(_translate("manager", "Thanh toán"))
        self.btn_add.setText(_translate("manager", "Add"))
        self.txt_b.setToolTip(_translate("manager", "<html><head/><body><p align=\"center\"><br/>SDSD</p></body></html>"))
        self.txt_b.setWhatsThis(_translate("manager", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.btn_upd.setText(_translate("manager", "Cập nhật"))
        self.btn_xoa.setText(_translate("manager", "Xóa bill"))
        self.label.setText(_translate("manager", "Bàn"))
        self.label_2.setText(_translate("manager", "Tổng tiền"))
        self.btn_b0.setText(_translate("manager", "MANG VỀ"))
        item = self.table_bill.horizontalHeaderItem(0)
        item.setText(_translate("manager", "Món"))
        item = self.table_bill.horizontalHeaderItem(1)
        item.setText(_translate("manager", "Số lượng"))
        item = self.table_bill.horizontalHeaderItem(2)
        item.setText(_translate("manager", "Đơn giá"))
        item = self.table_bill.horizontalHeaderItem(3)
        item.setText(_translate("manager", "Chú thích"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("manager", "Bán hàng"))
        item = self.table_bill_ngay.horizontalHeaderItem(0)
        item.setText(_translate("manager", "Tài khoản"))
        item = self.table_bill_ngay.horizontalHeaderItem(1)
        item.setText(_translate("manager", "Giờ"))
        item = self.table_bill_ngay.horizontalHeaderItem(2)
        item.setText(_translate("manager", "Bill"))
        item = self.table_bill_thang.horizontalHeaderItem(0)
        item.setText(_translate("manager", "Ngày"))
        item = self.table_bill_thang.horizontalHeaderItem(1)
        item.setText(_translate("manager", "Tổng tiền"))
        self.btn_add_2.setText(_translate("manager", "Thêm"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("manager", "Doanh thu"))
        item = self.table_menu.horizontalHeaderItem(0)
        item.setText(_translate("manager", "Món"))
        item = self.table_menu.horizontalHeaderItem(1)
        item.setText(_translate("manager", "Giá"))
        self.label_8.setText(_translate("manager", "Tên món:"))
        self.label_9.setText(_translate("manager", "Giá: "))
        self.btn_upd_menu.setText(_translate("manager", "Cập nhật"))
        self.label_10.setText(_translate("manager", "Cập nhật Menu"))
        self.lbl_menu.setText(_translate("manager", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("manager", "Menu"))
        self.btn_logout.setText(_translate("manager", "Đăng xuất"))
        self.label_3.setText(_translate("manager", "Tên:"))
        self.label_5.setText(_translate("manager", "SĐT:"))
        self.label_6.setText(_translate("manager", "ID:"))
        self.label_7.setText(_translate("manager", "Mật khẩu:"))
        self.btn_add_acc.setText(_translate("manager", "Tạo"))
        item = self.table_acc.horizontalHeaderItem(0)
        item.setText(_translate("manager", "Tên"))
        item = self.table_acc.horizontalHeaderItem(1)
        item.setText(_translate("manager", "SDT"))
        item = self.table_acc.horizontalHeaderItem(2)
        item.setText(_translate("manager", "ID"))
        item = self.table_acc.horizontalHeaderItem(3)
        item.setText(_translate("manager", "Mật khẩu"))
        self.label_4.setText(_translate("manager", "Tạo tài khoản"))
        self.lbl_acc.setText(_translate("manager", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("manager", "Quản lý nhân viên"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    manager = QtWidgets.QMainWindow()
    ui = Ui_manager()
    ui.setupUi(manager)
    manager.show()
    sys.exit(app.exec_())
